<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Assets\Icons\smartserve.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="appsettings.json" />
    <None Remove="Migrations\001_initial_schema.sql" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Migrations\001_initial_schema.sql" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\SmartServeCommon\SmartServe.Common\SmartServe.Common.csproj" />
    <ProjectReference Include="..\..\SmartServeCommon\SmartServe.Domain\SmartServe.Domain.csproj" />
    <ProjectReference Include="..\..\SmartServeCommon\SmartServe.EFCore\SmartServe.EFCore.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="12.0.1" />
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.0" />
    <PackageReference Include="HandyControl" Version="3.5.1" />
    <PackageReference Include="HandyControl.Lang.en" Version="3.5.1" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="8.0.23" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\Icons\smartserve.ico">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

</Project>
